eureka:
  client:
    service-url:http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    username: root
    password: Arkssvv@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Local development CORS configuration
app:
  cors:
    # Allow local development origins
    allowed-origins: "http://localhost:3000,http://localhost:8080,http://localhost:9090,http://localhost:4200"
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600