name: Dependency Update Check

on:
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Check for dependency updates
      run: mvn versions:display-dependency-updates
      
    - name: Check for plugin updates
      run: mvn versions:display-plugin-updates
      
    - name: Generate dependency tree
      run: mvn dependency:tree > dependency-tree.txt
      
    - name: Upload dependency report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-reports
        path: |
          dependency-tree.txt
          target/dependency-check-report.html